// This file only contains backwards compatibility.
// New code should be added to the respective module built to replace this!

class SYB_Tablets_ColorBase;
class SYB_Tablets_Analgin;
class SYB_Tablets_Naiz;
class SYB_Tablets_Aertal;
class SYB_Tablets_Nimesil;
class SYB_Tablets_Pentalgin;
class SYB_Tablets_Movalis;
class SYB_Tablets_Cytramon;
class SYB_Tablets_Paracetamol;
class SYB_Tablets_Ibuprofen;
class SYB_Tablets_Nurofen;
class SYB_Tablets_Tetracycline;
class SYB_Tablets_Amoksiklav;
class SYB_Tablets_Ampicylin;
class SYB_Tablets_Piperacylin;
class SYB_Tablets_Trihopol;
class SYB_Tablets_Cyprolet;
class SYB_Tablets_Amoksivan;
class SYB_Tablets_Amibaktam;
class SYB_Tablets_Charcoal;
class SYB_Tablets_MezimForte;
class SYB_Tablets_Zerukal;
class SYB_Tablets_Nifuroksazid;
class SYB_Tablets_Polisorb;
class SYB_Tablets_Karbopekt;
class SYB_Tablets_Enterofuril;
class SYB_Tablets_Ersefuril;
class SYB_Tablets_Salofalk;
class SYB_Tablets_Ftalazol;
class SYB_Tablets_Mesalazin;
class SYB_Tablets_Noopept;
class SYB_Tablets_Vikasol;
class SYB_Tablets_Dycinon;
class SYB_Tablets_Irovit;
class SYB_Tablets_Tardiferon;
class SYB_Tablets_Heferol;
class SYB_Tablets_SorbiferDurulis;
class SYB_Tablets_PotassiumIodide;
class SYB_Tablets_PotassiumHexacyanoferrate;
class SYB_Tablets_Cystamine;
class SYB_Tablets_B190;
class SYB_Tablets_Mexamine;
class SYB_Tablets_Agteminol;
class SYB_Tablets_Adepress;
class SYB_Tablets_Actaparoxetine;
class SYB_Tablets_Amitriptyline;
class SYB_Tablets_Venlafaxine;

class TabletsBase: SYB_Tablets_ColorBase {};
class TabletsAnalgin: SYB_Tablets_Analgin {};
class TabletsNaiz: SYB_Tablets_Naiz {};
class TabletsAertal: SYB_Tablets_Aertal {};
class TabletsNimesil: SYB_Tablets_Nimesil {};
class TabletsPentalgin: SYB_Tablets_Pentalgin {};
class TabletsMovalis: SYB_Tablets_Movalis {};
class TabletsCytramon: SYB_Tablets_Cytramon {};
class TabletsParacetamol: SYB_Tablets_Paracetamol {};
class TabletsIbuprofen: SYB_Tablets_Ibuprofen {};
class TabletsNurofen: SYB_Tablets_Nurofen {};
class TabletsTetracycline: SYB_Tablets_Tetracycline {};
class TabletsAmoksiklav: SYB_Tablets_Amoksiklav {};
class TabletsAmpicylin: SYB_Tablets_Ampicylin {};
class TabletsPiperacylin: SYB_Tablets_Piperacylin {};
class TabletsTrihopol: SYB_Tablets_Trihopol {};
class TabletsCyprolet: SYB_Tablets_Cyprolet {};
class TabletsAmoksivan: SYB_Tablets_Amoksivan {};
class TabletsAmibaktam: SYB_Tablets_Amibaktam {};
class TabletsCharcoal: SYB_Tablets_Charcoal {};
class TabletsMezimForte: SYB_Tablets_MezimForte {};
class TabletsZerukal: SYB_Tablets_Zerukal {};
class TabletsNifuroksazid: SYB_Tablets_Nifuroksazid {};
class TabletsPolisorb: SYB_Tablets_Polisorb {};
class TabletsKarbopekt: SYB_Tablets_Karbopekt {};
class TabletsEnterofuril: SYB_Tablets_Enterofuril {};
class TabletsErsefuril: SYB_Tablets_Ersefuril {};
class TabletsSalofalk: SYB_Tablets_Salofalk {};
class TabletsFtalazol: SYB_Tablets_Ftalazol {};
class TabletsMesalazin: SYB_Tablets_Mesalazin {};
class TabletsNoopept: SYB_Tablets_Noopept {};
class TabletsVikasol: SYB_Tablets_Vikasol {};
class TabletsDycinon: SYB_Tablets_Dycinon {};
class TabletsIrovit: SYB_Tablets_Irovit {};
class TabletsTardiferon: SYB_Tablets_Tardiferon {};
class TabletsHeferol: SYB_Tablets_Heferol {};
class TabletsSorbiferDurulis: SYB_Tablets_SorbiferDurulis {};
class TabletsPotassiumIodide: SYB_Tablets_PotassiumIodide {};
class TabletsPotassiumHexacyanoferrate: SYB_Tablets_PotassiumHexacyanoferrate {};
class TabletsCystamine: SYB_Tablets_Cystamine {};
class TabletsB190: SYB_Tablets_B190 {};
class TabletsMexamine: SYB_Tablets_Mexamine {};
class TabletsAgteminol: SYB_Tablets_Agteminol {};
class TabletsAdepress: SYB_Tablets_Adepress {};
class TabletsActaparoxetine: SYB_Tablets_Actaparoxetine {};
class TabletsAmitriptyline: SYB_Tablets_Amitriptyline {};
class TabletsVenlafaxine: SYB_Tablets_Venlafaxine {};