// This file only contains backwards compatibility.
// New code should be added to the respective module built to replace this!

class SYB_MedicineVial_ColorBase;
class SYB_MedicineVial_Alcohol;
class SYB_MedicineVial_Hihlofos;
class SYB_MedicineVial_Cypermetrin;
class SYB_MedicineVial_Diazinon;
class SYB_MedicineVial_Arsenic;
class SYB_MedicineVial_Novocain;
class SYB_MedicineVial_Irineks;
class SYB_MedicineVial_Nimesulid;
class SYB_MedicineVial_Ketoprofen;
class SYB_MedicineVial_Propofol;
class SYB_MedicineVial_Tiopental;
class SYB_MedicineVial_Ketamin;
class SYB_MedicineVial_Propanidid;
class SYB_MedicineVial_Gexobarbital;
class SYB_MedicineVial_SodiumOxybutirate;
class SYB_MedicineVial_Metoclopramid;
class SYB_MedicineVial_Zerukal;
class SYB_MedicineVial_Ketorol;
class SYB_MedicineVial_Diklofenak;
class SYB_MedicineVial_Heptral;
class SYB_MedicineVial_Cylaspen;
class SYB_MedicineVial_Grimipenem;
class SYB_MedicineVial_Zeftriaxon;
class SYB_MedicineVial_Erytromicyn;
class SYB_MedicineVial_Flemoclav;
class SYB_MedicineVial_Ocsacylin;
class SYB_MedicineVial_Imipenem;
class SYB_MedicineVial_Amoksivan;
class SYB_MedicineVial_Zivirol;
class SYB_MedicineVial_Meksidol;
class SYB_MedicineVial_Actovegin;
class SYB_MedicineVial_Neiroks;
class SYB_MedicineVial_Peklitakcel;
class SYB_MedicineVial_NonacogAlpha;
class SYB_MedicineVial_AminokaprolSulfat;
class SYB_MedicineVial_Vikasol;
class SYB_MedicineVial_Etamzilat;
class SYB_MedicineVial_Perftoran;
class SYB_MedicineVial_Maltofer;
class SYB_MedicineVial_Erytropoenin;
class SYB_MedicineVial_Adrenalin05;
class SYB_MedicineVial_Adrenalin10;
class SYB_MedicineVial_Adrenalin30;
class SYB_MedicineVial_Pentacin;
class SYB_MedicineVial_Carboxyme;
class SYB_MedicineVial_Metralindol;
class SYB_MedicineVial_Actaparoxetine;
class SYB_MedicineVial_Amitriptyline;

class SyberiaMedicineAmpoule: SYB_MedicineVial_ColorBase {};

class AmpouleAlcohol: SYB_MedicineVial_Alcohol {};
class AmpouleHihlofos: SYB_MedicineVial_Hihlofos {};
class AmpouleCypermetrin: SYB_MedicineVial_Cypermetrin {};
class AmpouleDiazinon: SYB_MedicineVial_Diazinon {};
class AmpouleArsenic: SYB_MedicineVial_Arsenic {};
class AmpouleNovocain: SYB_MedicineVial_Novocain {};
class AmpouleIrineks: SYB_MedicineVial_Irineks {};
class AmpouleNimesulid: SYB_MedicineVial_Nimesulid {};
class AmpouleKetoprofen: SYB_MedicineVial_Ketoprofen {};
class AmpoulePropofol: SYB_MedicineVial_Propofol {};
class AmpouleTiopental: SYB_MedicineVial_Tiopental {};
class AmpouleKetamin: SYB_MedicineVial_Ketamin {};
class AmpoulePropanidid: SYB_MedicineVial_Propanidid {};
class AmpouleGexobarbital: SYB_MedicineVial_Gexobarbital {};
class AmpouleSodiumOxybutirate: SYB_MedicineVial_SodiumOxybutirate {};
class AmpouleMetoclopramid: SYB_MedicineVial_Metoclopramid {};
class AmpouleZerukal: SYB_MedicineVial_Zerukal {};
class AmpouleKetorol: SYB_MedicineVial_Ketorol {};
class AmpouleDiklofenak: SYB_MedicineVial_Diklofenak {};
class AmpouleHeptral: SYB_MedicineVial_Heptral {};
class AmpouleCylaspen: SYB_MedicineVial_Cylaspen {};
class AmpouleGrimipenem: SYB_MedicineVial_Grimipenem {};
class AmpouleZeftriaxon: SYB_MedicineVial_Zeftriaxon {};
class AmpouleErytromicyn: SYB_MedicineVial_Erytromicyn {};
class AmpouleFlemoclav: SYB_MedicineVial_Flemoclav {};
class AmpouleOcsacylin: SYB_MedicineVial_Ocsacylin {};
class AmpouleImipenem: SYB_MedicineVial_Imipenem {};
class AmpouleAmoksivan: SYB_MedicineVial_Amoksivan {};
class AmpouleZivirol: SYB_MedicineVial_Zivirol {};
class AmpouleMeksidol: SYB_MedicineVial_Meksidol {};
class AmpouleActovegin: SYB_MedicineVial_Actovegin {};
class AmpouleNeiroks: SYB_MedicineVial_Neiroks {};
class AmpoulePeklitakcel: SYB_MedicineVial_Peklitakcel {};
class AmpouleNonacogAlpha: SYB_MedicineVial_NonacogAlpha {};
class AmpouleAminokaprolSulfat: SYB_MedicineVial_AminokaprolSulfat {};
class AmpouleVikasol: SYB_MedicineVial_Vikasol {};
class AmpouleEtamzilat: SYB_MedicineVial_Etamzilat {};
class AmpoulePerftoran: SYB_MedicineVial_Perftoran {};
class AmpouleMaltofer: SYB_MedicineVial_Maltofer {};
class AmpouleErytropoenin: SYB_MedicineVial_Erytropoenin {};
class AmpouleAdrenalin05: SYB_MedicineVial_Adrenalin05 {};
class AmpouleAdrenalin10: SYB_MedicineVial_Adrenalin10 {};
class AmpouleAdrenalin30: SYB_MedicineVial_Adrenalin30 {};
class AmpoulePentacin: SYB_MedicineVial_Pentacin {};
class AmpouleCarboxyme: SYB_MedicineVial_Carboxyme {};
class AmpouleMetralindol: SYB_MedicineVial_Metralindol {};
class AmpouleActaparoxetine: SYB_MedicineVial_Actaparoxetine {};
class AmpouleAmitriptyline: SYB_MedicineVial_Amitriptyline {};